name: Android Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Download Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
        unzip -d /opt/gradle gradle-7.5-bin.zip
        echo "GRADLE_HOME=/opt/gradle/gradle-7.5" >> $GITHUB_ENV
        echo "/opt/gradle/gradle-7.5/bin" >> $GITHUB_PATH
        
    - name: Build with Gradle
      run: |
        gradle wrapper
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk 